const recipes = [
    {
      id: 1,
      name: "Classic Pancakes",
      ingredients: {
        flour: "1 cup",
        sugar: "2 tbsp",
        salt: "1/4 tsp",
        milk: "1 cup",
        egg: "1",
        butter: "2 tbsp (molten)"
      },
      instructions: "Mix the dry ingredients in a bowl. Add the wet ingredients and whisk until smooth. Cook in a hot pan until golden brown on both sides.",
      preparationTime: "15 minutes",
      vegetarian: "yes",
      vegan: "no",
      difficulty: "easy",
      portions: 4,
      calories: 120,
      image: "./img/pancakes.jpg",
      origin: "american"
    },
    {
      id: 2,
      name: "Spaghetti Carbonara",
      ingredients: {
        spaghetti: "400g",
        pancetta: "150g",
        eggs: "3 (2 whole, 1 yolk)",
        parmesan: "50g (grated)",
        blackPepper: "to taste",
        salt: "to taste"
      },
      instructions: "Cook spaghetti in salted water. Fry pancetta until crispy. Mix eggs, parmesan, and pepper in a bowl. Toss hot spaghetti with pancetta and remove from heat. Stir in egg mixture until creamy.",
      preparationTime: "25 minutes",
      vegetarian: "no",
      vegan: "no",
      difficulty: "medium",
      portions: 4,
      calories: 450,
      image: "./img/spaghetti-carbonara.jpg",
      origin: "italian"
    },
    {
      id: 3,
      name: "Vegetable Stir Fry",
      ingredients: {
        bellPepper: "1 (sliced)",
        broccoli: "1 cup (florets)",
        carrot: "1 (julienned)",
        soySauce: "2 tbsp",
        garlic: "2 cloves (minced)",
        ginger: "1 tsp (minced)",
        oliveOil: "2 tbsp"
      },
      instructions: "Heat oil in a wok. Add garlic and ginger, stir-fry briefly. Add vegetables and cook until tender. Stir in soy sauce and cook for another minute. Serve hot.",
      preparationTime: "20 minutes",
      vegetarian: "yes",
      vegan: "yes",
      difficulty: "easy",
      portions: 2,
      calories: 200,
      image: "./img/vegetable-stir-fry.jpg",
      origin: "asian"
    },
    {
      id: 4,
      name: "Chicken Curry",
      ingredients: {
        chicken: "500g (boneless, cubed)",
        onion: "1 (chopped)",
        garlic: "2 cloves (minced)",
        curryPowder: "2 tbsp",
        coconutMilk: "1 cup",
        tomatoPaste: "2 tbsp",
        oil: "2 tbsp",
        salt: "to taste"
      },
      instructions: "Heat oil in a pot. Sauté onion and garlic until soft. Add chicken and cook until browned. Stir in curry powder and tomato paste. Pour in coconut milk and simmer until chicken is cooked through.",
      preparationTime: "40 minutes",
      vegetarian: "no",
      vegan: "no",
      difficulty: "medium",
      portions: 4,
      calories: 320,
      image: "./img/chicken-curry.jpg",
      origin: "indian"
    },
    {
      id: 5,
      name: "Avocado Toast",
      ingredients: {
        bread: "2 slices",
        avocado: "1 (mashed)",
        lemonJuice: "1 tsp",
        oliveOil: "1 tsp",
        salt: "to taste",
        pepper: "to taste"
      },
      instructions: "Toast the bread until golden brown. Mash avocado with lemon juice, olive oil, salt, and pepper. Spread mixture over the toast and serve immediately.",
      preparationTime: "10 minutes",
      vegetarian: "yes",
      vegan: "yes",
      difficulty: "easy",
      portions: 1,
      calories: 250,
      image: "./img/avocado-toast.jpg",
      origin: "californian"
    },
    {
        id: 6,
        name: "Tomato Basil Soup",
        ingredients: {
          tomatoes: "6 (large, diced)",
          onion: "1 (chopped)",
          garlic: "2 cloves (minced)",
          vegetableStock: "2 cups",
          basil: "1/4 cup (fresh, chopped)",
          oliveOil: "2 tbsp",
          salt: "to taste",
          pepper: "to taste"
        },
        instructions: "Heat olive oil in a pot. Sauté onion and garlic until soft. Add tomatoes and cook until softened. Pour in vegetable stock and simmer for 15 minutes. Blend until smooth, then stir in fresh basil. Serve warm.",
        preparationTime: "30 minutes",
        vegetarian: "yes",
        vegan: "yes",
        difficulty: "easy",
        portions: 4,
        calories: 150,
        image: "./img/tomato-basil-soup.jpg",
        origin: "italian"
      },
      {
        id: 7,
        name: "Beef Tacos",
        ingredients: {
          groundBeef: "500g",
          tacoSeasoning: "2 tbsp",
          tortillas: "8 (small)",
          lettuce: "1 cup (shredded)",
          tomato: "1 (diced)",
          cheese: "1/2 cup (shredded)",
          sourCream: "1/4 cup"
        },
        instructions: "Cook ground beef in a skillet until browned. Add taco seasoning and a splash of water, then simmer until thickened. Assemble tacos with beef, lettuce, tomato, cheese, and sour cream.",
        preparationTime: "20 minutes",
        vegetarian: "no",
        vegan: "no",
        difficulty: "easy",
        portions: 4,
        calories: 300,
        image: "./img/beef-tacos.jpg",
        origin: "mexican"
      },
      {
        id: 8,
        name: "Greek Salad",
        ingredients: {
          cucumber: "1 (sliced)",
          tomato: "2 (diced)",
          redOnion: "1/2 (thinly sliced)",
          fetaCheese: "1/2 cup (crumbled)",
          olives: "1/4 cup",
          oliveOil: "2 tbsp",
          lemonJuice: "1 tbsp",
          oregano: "1 tsp",
          salt: "to taste",
          pepper: "to taste"
        },
        instructions: "Combine cucumber, tomato, red onion, feta cheese, and olives in a bowl. Whisk together olive oil, lemon juice, oregano, salt, and pepper. Pour dressing over salad and toss to combine.",
        preparationTime: "15 minutes",
        vegetarian: "yes",
        vegan: "no",
        difficulty: "easy",
        portions: 2,
        calories: 200,
        image: "./img/greek-salad.jpg",
        origin: "greek"
      },
      {
        id: 9,
        name: "Chocolate Chip Cookies",
        ingredients: {
          flour: "2 1/4 cups",
          sugar: "3/4 cup",
          brownSugar: "3/4 cup",
          butter: "1 cup (softened)",
          egg: "2",
          vanillaExtract: "1 tsp",
          bakingSoda: "1 tsp",
          salt: "1/2 tsp",
          chocolateChips: "2 cups"
        },
        instructions: "Preheat oven to 375°F (190°C). Cream together butter, sugar, and brown sugar. Mix in eggs and vanilla. Combine dry ingredients and mix into wet ingredients. Fold in chocolate chips. Drop spoonfuls onto a baking sheet and bake for 10-12 minutes.",
        preparationTime: "25 minutes",
        vegetarian: "yes",
        vegan: "no",
        difficulty: "medium",
        portions: 24,
        calories: 100,
        image: "./img/chocolate-chip-cookies.jpg",
        origin: "american"
      },
      {
        id: 10,
        name: "Shrimp Pad Thai",
        ingredients: {
          riceNoodles: "200g",
          shrimp: "250g (peeled and deveined)",
          egg: "1 (beaten)",
          beanSprouts: "1 cup",
          greenOnion: "1/4 cup (chopped)",
          peanuts: "2 tbsp (crushed)",
          fishSauce: "2 tbsp",
          tamarindPaste: "1 tbsp",
          sugar: "1 tbsp",
          lime: "1 (wedged)"
        },
        instructions: "Cook rice noodles according to package instructions. Stir-fry shrimp in a hot pan. Push to the side and scramble the egg. Add noodles, fish sauce, tamarind paste, and sugar. Stir-fry until combined. Top with bean sprouts, green onion, peanuts, and a squeeze of lime.",
        preparationTime: "30 minutes",
        vegetarian: "no",
        vegan: "no",
        difficulty: "medium",
        portions: 2,
        calories: 400,
        image: "./img/shrimp-pad-thai.jpg",
        origin: "thai"
      },
      {
        id: 11,
        name: "Margherita Pizza",
        ingredients: {
          pizzaDough: "1 (12-inch)",
          tomatoSauce: "1/2 cup",
          mozzarella: "1 cup (sliced)",
          basil: "8 leaves (fresh)",
          oliveOil: "1 tbsp"
        },
        instructions: "Preheat oven to 475°F (245°C). Spread tomato sauce over pizza dough. Top with mozzarella slices and fresh basil. Drizzle with olive oil. Bake for 10-12 minutes until crust is golden and cheese is bubbling.",
        preparationTime: "20 minutes",
        vegetarian: "yes",
        vegan: "no",
        difficulty: "medium",
        portions: 2,
        calories: 300,
        image: "./img/margherita-pizza.jpg",
        origin: "italian"
      },
      {
        id: 12,
        name: "Butter Chicken",
        ingredients: {
          chicken: "500g (boneless, cubed)",
          yogurt: "1/2 cup",
          garlic: "2 cloves (minced)",
          ginger: "1 tsp (minced)",
          butter: "2 tbsp",
          tomatoPuree: "1/2 cup",
          cream: "1/4 cup",
          garamMasala: "1 tsp",
          turmeric: "1/2 tsp",
          chiliPowder: "1/2 tsp",
          salt: "to taste"
        },
        instructions: "Marinate chicken in yogurt, garlic, ginger, and spices for 30 minutes. Sear in butter until golden. Add tomato puree and simmer for 15 minutes. Stir in cream and simmer for another 5 minutes. Serve with naan or rice.",
        preparationTime: "45 minutes",
        vegetarian: "no",
        vegan: "no",
        difficulty: "medium",
        portions: 4,
        calories: 350,
        image: "./img/butter-chicken.jpg",
        origin: "indian"
      },
      {
        id: 13,
        name: "Guacamole",
        ingredients: {
          avocado: "2 (ripe)",
          limeJuice: "1 tbsp",
          tomato: "1 (diced)",
          redOnion: "1/4 cup (chopped)",
          cilantro: "2 tbsp (chopped)",
          jalapeno: "1 (optional, minced)",
          salt: "to taste"
        },
        instructions: "Mash avocados in a bowl. Stir in lime juice, tomato, red onion, cilantro, and jalapeño. Add salt to taste. Serve immediately with tortilla chips or as a topping.",
        preparationTime: "10 minutes",
        vegetarian: "yes",
        vegan: "yes",
        difficulty: "easy",
        portions: 4,
        calories: 150,
        image: "./img/guacamole.jpg",
        origin: "mexican"
      },
      {
        id: 14,
        name: "Vegetable Curry",
        ingredients: {
          cauliflower: "1 cup (florets)",
          potato: "1 (diced)",
          carrot: "1 (sliced)",
          coconutMilk: "1 cup",
          curryPowder: "2 tbsp",
          garlic: "2 cloves (minced)",
          ginger: "1 tsp (minced)",
          oil: "2 tbsp",
          salt: "to taste",
          cilantro: "2 tbsp (chopped)"
        },
        instructions: "Heat oil in a pot and sauté garlic and ginger. Add vegetables and stir-fry for 5 minutes. Sprinkle with curry powder, then pour in coconut milk. Simmer until vegetables are tender. Garnish with cilantro and serve.",
        preparationTime: "35 minutes",
        vegetarian: "yes",
        vegan: "yes",
        difficulty: "medium",
        portions: 4,
        calories: 250,
        image: "./img/vegetable-curry.jpg",
        origin: "indian"
      },
      {
        id: 15,
        name: "Caprese Salad",
        ingredients: {
          tomato: "2 (sliced)",
          mozzarella: "200g (sliced)",
          basil: "10 leaves (fresh)",
          oliveOil: "2 tbsp",
          balsamicGlaze: "1 tbsp",
          salt: "to taste",
          pepper: "to taste"
        },
        instructions: "Layer slices of tomato and mozzarella on a plate, alternating each slice. Tuck basil leaves between layers. Drizzle with olive oil and balsamic glaze. Sprinkle with salt and pepper before serving.",
        preparationTime: "10 minutes",
        vegetarian: "yes",
        vegan: "no",
        difficulty: "easy",
        portions: 2,
        calories: 200,
        image: "./img/caprese-salad.jpg",
        origin: "italian"
      },
      {
        id: 16,
        name: "French Omelette",
        ingredients: {
          eggs: "3",
          butter: "1 tbsp",
          milk: "1 tbsp",
          salt: "to taste",
          pepper: "to taste",
          chives: "1 tbsp (optional, chopped)"
        },
        instructions: "Whisk eggs, milk, salt, and pepper until well combined. Heat butter in a non-stick pan over medium heat. Pour eggs into the pan and stir gently until almost set. Fold into an omelette and slide onto a plate. Garnish with chives if desired.",
        preparationTime: "10 minutes",
        vegetarian: "yes",
        vegan: "no",
        difficulty: "easy",
        portions: 1,
        calories: 200,
        image: "./img/french-omelette.jpg",
        origin: "french"
      },
      {
        id: 17,
        name: "Caesar Salad",
        ingredients: {
          romaineLettuce: "1 head (chopped)",
          croutons: "1 cup",
          parmesan: "1/4 cup (grated)",
          caesarDressing: "1/3 cup",
          chickenBreast: "1 (grilled, sliced, optional)"
        },
        instructions: "Combine lettuce, croutons, and parmesan in a bowl. Toss with Caesar dressing until evenly coated. Top with grilled chicken if desired and serve immediately.",
        preparationTime: "15 minutes",
        vegetarian: "yes (without chicken)",
        vegan: "no",
        difficulty: "easy",
        portions: 2,
        calories: 300,
        image: "./img/caesar-salad.jpg",
        origin: "american"
      },
      {
        id: 18,
        name: "Stuffed Bell Peppers",
        ingredients: {
          bellPeppers: "4 (halved and seeded)",
          groundBeef: "500g",
          rice: "1 cup (cooked)",
          tomatoSauce: "1 cup",
          onion: "1 (chopped)",
          garlic: "2 cloves (minced)",
          mozzarella: "1/2 cup (shredded)"
        },
        instructions: "Preheat oven to 375°F (190°C). Sauté beef, onion, and garlic until browned. Stir in rice and tomato sauce. Stuff peppers with the mixture and top with mozzarella. Bake for 25 minutes or until peppers are tender.",
        preparationTime: "45 minutes",
        vegetarian: "no",
        vegan: "no",
        difficulty: "medium",
        portions: 4,
        calories: 350,
        image: "./img/stuffed-bell-peppers.jpg",
        origin: "mediterranean"
      },
      {
        id: 19,
        name: "Banana Smoothie",
        ingredients: {
          banana: "1 (ripe)",
          milk: "1 cup",
          yogurt: "1/2 cup",
          honey: "1 tbsp",
          iceCubes: "4"
        },
        instructions: "Combine all ingredients in a blender and blend until smooth. Pour into a glass and serve immediately.",
        preparationTime: "5 minutes",
        vegetarian: "yes",
        vegan: "no (can be vegan with plant-based milk and yogurt)",
        difficulty: "easy",
        portions: 1,
        calories: 150,
        image: "./img/banana-smoothie.jpg",
        origin: "global"
      },
      {
        id: 20,
        name: "Garlic Bread",
        ingredients: {
          baguette: "1 (sliced)",
          butter: "1/2 cup (softened)",
          garlic: "2 cloves (minced)",
          parsley: "2 tbsp (chopped)",
          parmesan: "2 tbsp (grated, optional)"
        },
        instructions: "Preheat oven to 375°F (190°C). Mix butter, garlic, parsley, and parmesan. Spread mixture on baguette slices. Arrange slices on a baking sheet and bake for 10 minutes or until golden and crispy.",
        preparationTime: "15 minutes",
        vegetarian: "yes",
        vegan: "no",
        difficulty: "easy",
        portions: 4,
        calories: 200,
        image: "./img/garlic-bread.jpg",
        origin: "italian"
      }
  ];
  
  
export default recipes;